namespace MonsterHunterWilds
{
    // Skills
    enum SkillKind
    {
        Armor,
        Weapon,
        Set,
        Group
    };

    enum SkillIconKind
    {
        Affinity,
        Attack,
        Defense,
        Element,
        Gathering,
        Group,
        Handicraft,
        Health,
        Item,
        Offense,
        Ranged,
        Set,
        Stamina,
        Utility
    };

    runtimeclass SkillIcon
    {
        static SkillIcon Parse(Windows.Data.Json.JsonObject json_object);
        static SkillIcon TryParse(Windows.Data.Json.JsonObject json_object, String key);

        SkillIcon(Int32 game_id, SkillIconKind kind);

        Int32 GameId{ get; };
        SkillIconKind Kind{ get; };
    }

    runtimeclass SkillRank
    {
        static SkillRank Parse(Windows.Data.Json.JsonObject json_object);
        static Windows.Foundation.Collections.IVector<SkillRank> TryParse(Windows.Data.Json.JsonObject json_object, String key);

		SkillRank(Int32 id, String name, String description, Int32 level);

		Int32 Id{ get; };
	    String Name{ get; };
		String Description{ get; };
		Int32 Level{ get; };
    }

    runtimeclass Skill
    {
        static Skill Parse(Windows.Data.Json.JsonObject json_object);

		Skill(Int32 id, String name, String description, Windows.Foundation.Collections.IVector<SkillRank> ranks, Windows.Foundation.IReference<SkillKind> kind, SkillIcon icon);

		Int32 Id{ get; };
	    String Name{ get; };
		String Description{ get; };
		Windows.Foundation.Collections.IVector<SkillRank> Ranks{ get; };
		Windows.Foundation.IReference<SkillKind> Kind{ get; };
		SkillIcon Icon{ get; };
    }

    // Items
    runtimeclass ItemRecipe
    {
        static ItemRecipe Parse(Windows.Data.Json.JsonObject json_object);

        ItemRecipe(Int32 id, Int32 amount, Windows.Foundation.Collections.IVector<Item> inputs);

		Int32 Id{ get; };
	    Int32 Amount{ get; };
		Windows.Foundation.Collections.IVector<Item> Inputs{ get; };
    }

    enum Color
    {
        White,
        Gray,
        Rose,
        Pink,
        Red,
        Vermilion,
        Orange,
        Brwon,
        Brown,
        Ivory,
        Yellow,
        Lemon,
        SageGreen,
        MossGreen,
        Green,
        Emerald,
        Sky,
        Blue,
        Ultramarine,
        BluePurple,
        Purple,
		DarkPurple
	};

    enum ItemIconKind
    {
        AmmoBasic,
        AmmoHeavy,
        AmmoSlug,
        AmmoSpecial,
        AmmoUtility,
        ArmorSphere,
        Barrel,
        Binoculars,
        Bomb,
        Bone,
        Bug,
        CampingKit,
        CaptureNet,
        Certificate,
        Claw,
        Coin,
        CookingCheese,
        CookingEgg,
        CookingGarlic,
        CookingMushroom,
        CookingShellfish,
        Crystal,
        Curative,
        Drug,
        Egg,
        Extract,
        FishingRod,
        Fish,
        Gem,
        Grill,
        Hide,
        Honey,
        Mantle,
        Meat,
        Medulla,
        Mushroom,
        MysteryArtian,
        MysteryDecoration,
        MysteryMaterial,
        Nut,
        Ore,
        Phial,
        Pill,
        Plant,
        Plate,
        Poop,
        Potion,
        Powder,
        Question,
        Scale,
        Seed,
        Shell,
        Skull,
        SlingerAmmo,
        Smoke,
        Sprout,
        Tail,
        Trap,
        TrapTool,
        Unknown,
        Voucher,
        Web,
        Whetstone,
        Wing,
        Knife
    };

    runtimeclass ItemIcon
    {
        static ItemIcon Parse(Windows.Data.Json.JsonObject json_object);

        ItemIcon(Int32 game_id, ItemIconKind kind, Windows.Foundation.IReference<Int32> color_id, Color color);

		Int32 GameId{ get; };
        ItemIconKind Kind{ get; };
		Windows.Foundation.IReference<Int32> ColorId{ get; };
		Color Color{ get; };
    }

    runtimeclass Item
    {
        static Item Parse(Windows.Data.Json.JsonObject json_object);

        Item(Int32 id, Int32 game_id, String name, String description, Int32 rarity, Int32 carry_limit, Int32 the_value, Windows.Foundation.Collections.IVector<ItemRecipe> recipes, ItemIcon icon);

        Int32 Id{ get; };
        Int32 GameId{ get; };
        String Name{ get; };
        String Description{ get; };
        Int32 Rarity{ get; };
        Int32 CarryLimit{ get; };
        Int32 Value{ get; };
        Windows.Foundation.Collections.IVector<ItemRecipe> Recipes{ get; };
        ItemIcon Icon{ get; };
    }

    // Armor
    enum ArmorKind
    {
        Head,
        Chest,
        Arms,
        Waist,
        Legs
	};

    runtimeclass ArmorDefense
    {
        static ArmorDefense Parse(Windows.Data.Json.JsonObject json_object);

        ArmorDefense(Int32 base, Int32 max);

		Int32 Base{ get; };
	    Int32 Max{ get; };
    }

    runtimeclass ArmorResistances
    {
        static ArmorResistances Parse(Windows.Data.Json.JsonObject json_object);

        ArmorResistances(Int32 fire, Int32 water, Int32 ice, Int32 thunder, Int32 dragon);

		Int32 Fire{ get; };
	    Int32 Water{ get; };
		Int32 Ice{ get; };
		Int32 Thunder{ get; };
		Int32 Dragon{ get; };
    }

    runtimeclass ArmorCrafting
    {
        static ArmorCrafting Parse(Windows.Data.Json.JsonObject json_object);

		ArmorCrafting(Int32 id, Int32 zenny_cost, Windows.Foundation.Collections.IVector<CraftingCost> materials);

		Int32 Id{ get; };
	    Int32 ZennyCost{ get; };
        Windows.Foundation.Collections.IVector<CraftingCost> Materials{ get; };
    }

    enum Rank
    {
        Low,
        High,
        Master
	};

    runtimeclass Armor
    {
        static Armor Parse(Windows.Data.Json.JsonObject json_object);

        Armor(
            Int32 id,
            String name,
            String description,
            ArmorKind kind,
            Rank rank,
            Int32 rarity,
            ArmorDefense defense,
            ArmorResistances resistances,
            Windows.Foundation.Collections.IVector<Int32> slots,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            MiniArmorSet armor_set,
            ArmorCrafting crafting);

        Int32 Id{ get; };        
        String Name{ get; };
        String Description{ get; };
        ArmorKind Kind{ get; };
		Rank Rank{ get; };
        Int32 Rarity{ get; };
        ArmorDefense Defense{ get; };
        ArmorResistances Resistances{ get; };
        Windows.Foundation.Collections.IVector<Int32> Slots{ get; };
		Windows.Foundation.Collections.IVector<SkillRank> Skills{ get; };
        MiniArmorSet ArmorSet{ get; };
		ArmorCrafting Crafting{ get; };
    }

    // Armor Sets
    runtimeclass ArmorSetBonusRank
    {
        static ArmorSetBonusRank Parse(Windows.Data.Json.JsonObject json_object);

        ArmorSetBonusRank(Int32 id, Int32 pieces, SkillRank skill);

        Int32 Id{ get; };
        Int32 Pieces{ get; };
        SkillRank Skill{ get; };
    }

    runtimeclass ArmorSetBonus
    {
        static ArmorSetBonus Parse(Windows.Data.Json.JsonObject json_object);
        static ArmorSetBonus TryParse(Windows.Data.Json.JsonObject json_object, String key);

        ArmorSetBonus(Int32 id, Skill skill, Windows.Foundation.Collections.IVector<ArmorSetBonusRank> ranks);

		Int32 Id{ get; };
	    Skill Skill{ get; };
		Windows.Foundation.Collections.IVector<ArmorSetBonusRank> Ranks{ get; };
    }

    runtimeclass ArmorSet
    {
        static ArmorSet Parse(Windows.Data.Json.JsonObject json_object);

        ArmorSet(Int32 id, Int32 game_id, String name, Windows.Foundation.Collections.IVector<Armor> pieces, ArmorSetBonus bonus, ArmorSetBonus group_bonus);

        Int32 Id{ get; };
	    Int32 GameId{ get; };
        String Name{ get; };
		Windows.Foundation.Collections.IVector<Armor> Pieces{ get; };
		ArmorSetBonus Bonus{ get; };
		ArmorSetBonus GroupBonus{ get; };
	}

    // Armor JSON Object에서는 아래 것을 사용
    runtimeclass MiniArmorSet
    {
        static MiniArmorSet Parse(Windows.Data.Json.JsonObject json_object);

        MiniArmorSet(Int32 id, String name);

        Int32 Id{ get; };
        String Name{ get; };
    }

	// Charms
    runtimeclass CraftingCost
    {
        static CraftingCost Parse(Windows.Data.Json.JsonObject json_object);

        CraftingCost(Int32 quantity, Item item);

        Int32 Quantity{ get; };
        Item Item{ get; };
	}

    runtimeclass CharmRankCrafting
    {
        static CharmRankCrafting Parse(Windows.Data.Json.JsonObject json_object);

        CharmRankCrafting(Boolean craftable, Int32 zenny_cost, Windows.Foundation.Collections.IVector<CraftingCost> materials);

        Boolean Craftable{ get; };
        Int32 ZennyCost{ get; };
        Windows.Foundation.Collections.IVector<CraftingCost> Materials{ get; };
    }

    runtimeclass CharmRank
    {
        static CharmRank Parse(Windows.Data.Json.JsonObject json_object);

        CharmRank(Int32 id, String name, String description, Int32 level, Int32 rarity, Windows.Foundation.Collections.IVector<SkillRank> skills, CharmRankCrafting crafting);

        Int32 Id{ get; };
        String Name{ get; };
        String Description{ get; };
        Int32 Level{ get; };
        Int32 Rarity{ get; };
        Windows.Foundation.Collections.IVector<SkillRank> Skills{ get; };
        CharmRankCrafting Crafting{ get; };
    }

    runtimeclass Charm
    {
        static Charm Parse(Windows.Data.Json.JsonObject json_object);

        Charm(Int32 id, Int32 game_id, Windows.Foundation.Collections.IVector<CharmRank> ranks);

        Int32 Id{ get; };
        Int32 GameId{ get; };
        Windows.Foundation.Collections.IVector<CharmRank> Ranks{ get; };
    }

	// Decorations
    enum DecorationKind
    {
        Weapon,
        Armor
    };

    runtimeclass DecorationIcon
    {
        static DecorationIcon Parse(Windows.Data.Json.JsonObject json_object);

        DecorationIcon(Color color, Int32 color_id);

        Color Color{ get; };
        Int32 ColorId{ get; };
    }

    runtimeclass Decoration
    {
        static Decoration Parse(Windows.Data.Json.JsonObject json_object);

        Decoration(
            Int32 id,
            Int32 game_id,
            String name,
            String description,
            Int32 slot,
            Int32 rarity,
            DecorationKind kind,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            DecorationIcon icon
        );

        Int32 Id{ get; };
        Int32 GameId{ get; };
        String Name{ get; };
        String Description{ get; };
        Int32 Slot{ get; };
        Int32 Rarity{ get; };
        DecorationKind Kind{ get; };
        Windows.Foundation.Collections.IVector<SkillRank> Skills{ get; };
        DecorationIcon Icon{ get; };
    }

    // Weapons
    [default_interface]
    runtimeclass Sharpness
    {
        static Sharpness Parse(Windows.Data.Json.JsonObject json_object);

        Sharpness();
        Sharpness(Int32 red, Int32 orange, Int32 yellow, Int32 green, Int32 blue, Int32 white, Int32 purple);

        Int32 Red{ get; };
        Int32 Orange{ get; };
        Int32 Yellow{ get; };
        Int32 Green{ get; };
        Int32 Blue{ get; };
        Int32 White{ get; };
        Int32 Purple{ get; };
    }

    enum Status
    {
        Poison,
        Sleep,
        Paralysis,
        Stun,
        Blastblight
    };

    enum Element
    {
        Fire,
        Water,
        Ice,
        Thunder,
        Dragon
	};

    enum SpecialKind
    {
        Element,
        Status
    };

    runtimeclass WeaponDamage
    {
        static WeaponDamage Parse(Windows.Data.Json.JsonObject json_object);

        WeaponDamage(Int32 raw, Int32 display);

		Int32 Raw{ get; };
	    Int32 Display{ get; };
    }

    interface WeaponSpecial
    {
		Int32 Id{ get; };
	    WeaponDamage Damage{ get; };
		Boolean Hidden{ get; };
        SpecialKind SpecialKind{ get; };
    }

    runtimeclass WeaponElement : WeaponSpecial
    {
        static WeaponElement Parse(Windows.Data.Json.JsonObject json_object);

        WeaponElement(Int32 id, WeaponDamage damage, Boolean hidden, Element element);

		Element Element{ get; };
    }

    runtimeclass WeaponStatus : WeaponSpecial
    {
        static WeaponStatus Parse(Windows.Data.Json.JsonObject json_object);

        WeaponStatus(Int32 id, WeaponDamage damage, Boolean hidden, Status status);

		Status Status{ get; };
    }

    [default_interface]
    runtimeclass WeaponSeries
    {
        static WeaponSeries Parse(Windows.Data.Json.JsonObject json_object);

        WeaponSeries();
		WeaponSeries(Int32 id, Int32 game_id);

		Int32 Id{ get; };
        Int32 GameId{ get; };
    }

    enum WeaponKind
    {
        Bow,
        HuntingHorn,
        ChargeBlade,
		InsectGlaive,
		DualBlades,
        Lance,
		GreatSword,
		LightBowgun,
		Gunlance,
		LongSword,
		Hammer,
        SwitchAxe,
        HeavyBowgun,
        SwordShield
	};

    enum Elderseal
    {
        Low,
        Average,
        High
	};

    // WeaponCrafting JSON Object에서는 아래 것을 사용
    [default_interface]
    runtimeclass MiniWeapon
    {
        static MiniWeapon Parse(Windows.Data.Json.JsonObject json_object);

        MiniWeapon();
        MiniWeapon(
            Int32 id,
            String name
        );

        Int32 Id{ get; };
        String Name{ get; };
    }

    runtimeclass WeaponCrafting
    {
        static WeaponCrafting Parse(Windows.Data.Json.JsonObject json_object);

        WeaponCrafting(
            Int32 id,
            Boolean craftable,
            MiniWeapon previous,
            Windows.Foundation.Collections.IVector<MiniWeapon> branches,
            Int32 crafting_zenny_cost,
            Windows.Foundation.Collections.IVector<CraftingCost> crafting_materials,
            Int32 upgrade_zenny_cost,
            Windows.Foundation.Collections.IVector<CraftingCost> upgrade_materials,
            Int32 row,
            Int32 column);

        Int32 Id{ get; };
        Boolean Craftable{ get; };
        MiniWeapon Previous{ get; };
        Windows.Foundation.Collections.IVector<MiniWeapon> Branches{ get; };
        Int32 CraftingZennyCost{ get; };
        Windows.Foundation.Collections.IVector<CraftingCost> CraftingMaterials{ get; };
        Int32 UpgradeZennyCost{ get; };
        Windows.Foundation.Collections.IVector<CraftingCost> UpgradeMaterials{ get; };
        Int32 Row{ get; };
        Int32 Column{ get; };
    }

    interface Weapon
    {
		Int32 Id{ get; };
        Int32 GameId{ get; };
		WeaponKind Kind{ get; };
        String Name{ get; };
        Int32 Rarity{ get; };
        WeaponDamage Damage{ get; };
        Windows.Foundation.Collections.IVector<WeaponSpecial> Specials{ get; };
        Sharpness Sharpness{ get; };
		Windows.Foundation.Collections.IVector<Int32> Handicraft{ get; };
        Windows.Foundation.Collections.IVector<SkillRank> Skills{ get; };
		Int32 DefenseBonus{ get; };
		Windows.Foundation.IReference<Elderseal> Elderseal{ get; };
		Int32 Affinity{ get; };
        Windows.Foundation.Collections.IVector<Int32> Slots{ get; };
		WeaponCrafting Crafting{ get; };
		WeaponSeries Series{ get; };
    }

    enum BowCoating
    {
        CloseRange,
        Power,
        Pierce,
        Paralysis,
        Poison,
        Sleep,
        Blast,
        Exhaust
	};

    runtimeclass Bow : Weapon
    {
        static Bow Parse(Windows.Data.Json.JsonObject json_object);

        Bow(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series,
			Windows.Foundation.Collections.IVector<BowCoating> coatings
        );

		Windows.Foundation.Collections.IVector<BowCoating> Coatings{ get; };
    }

    enum HuntingHornNote
    {
        Purple,
        Red,
		Orange,
        Yellow,
        Green,
        Blue,
        Aqua,
        White
    };

    runtimeclass HuntingHornSong
    {
        static HuntingHornSong Parse(Windows.Data.Json.JsonObject json_object);

		HuntingHornSong(Int32 id, Int32 effect_id, Windows.Foundation.Collections.IVector<HuntingHornNote> sequence, String name);

        Int32 Id{ get; };
        Int32 EffectId{ get; };
        Windows.Foundation.Collections.IVector<HuntingHornNote> Sequence{ get; };
        String Name{ get; };
    }

    runtimeclass HuntingHornMelody
    {
        static HuntingHornMelody Parse(Windows.Data.Json.JsonObject json_object);

		HuntingHornMelody(Int32 id, Int32 game_id, Windows.Foundation.Collections.IVector<HuntingHornNote> notes, Windows.Foundation.Collections.IVector<HuntingHornSong> songs);

		Int32 Id{ get; };
	    Int32 GameId{ get; };
		Windows.Foundation.Collections.IVector<HuntingHornNote> Notes{ get; };
        Windows.Foundation.Collections.IVector<HuntingHornSong> Songs{ get; };
    }

    enum HuntingHornBubbleKind
    {
        Evasion,
        Damage,
        Regen,
        Defense,
        Stamina,
        Immunity
    };

    runtimeclass HuntingHornBubble
    {
        static HuntingHornBubble Parse(Windows.Data.Json.JsonObject json_object);

        HuntingHornBubble(Int32 id, Int32 game_id, HuntingHornBubbleKind kind, String name);

		Int32 Id{ get; };
        Int32 GameId{ get; };
        HuntingHornBubbleKind Kind{ get; };
		String Name{ get; };
    }

    enum HuntingHornWaveKind
    {
        Blunt,
        Slash,
        Fire,
        Water,
        Thunder,
        Ice,
        Dragon,
        Poison,
        Paralyze,
        Sleep,
        Blast
    };

    runtimeclass HuntingHornWave
    {
        static HuntingHornWave Parse(Windows.Data.Json.JsonObject json_object);
        static HuntingHornWave TryParse(Windows.Data.Json.JsonObject json_object, String key);

        HuntingHornWave(Int32 id, Int32 game_id, HuntingHornWaveKind kind, String name);

		Int32 Id{ get; };
        Int32 GameId{ get; };
		HuntingHornWaveKind Kind{ get; };
        String Name{ get; };
    }

    runtimeclass HuntingHorn : Weapon
    {
        static HuntingHorn Parse(Windows.Data.Json.JsonObject json_object);

        HuntingHorn(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
			Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
			Windows.Foundation.Collections.IVector<Int32> handicraft,
			Windows.Foundation.Collections.IVector<SkillRank> skills,
			Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
			Int32 affinity,
			Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
			WeaponSeries series,
			HuntingHornMelody melody,
			HuntingHornBubble echo_bubble,
            HuntingHornWave echo_wave
		);

        HuntingHornMelody Melody{ get; };
        HuntingHornBubble EchoBubble{ get; };
        HuntingHornWave EchoWave{ get; };
    }

    enum ChargeBladePhial
    {
        Element,
        Impact
	};

    runtimeclass ChargeBlade : Weapon
    {
        static ChargeBlade Parse(Windows.Data.Json.JsonObject json_object);

        ChargeBlade(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series,
            ChargeBladePhial phial
        );

        ChargeBladePhial Phial{ get; };
    }

    runtimeclass InsectGlaive : Weapon
    {
        static InsectGlaive Parse(Windows.Data.Json.JsonObject json_object);

        InsectGlaive(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
			WeaponCrafting crafting,
            WeaponSeries series,
            Int32 kinsect_level
        );

		Int32 KinsectLevel{ get; };
    }

    [default_interface]
    runtimeclass DualBlades : Weapon
    {
        static DualBlades Parse(Windows.Data.Json.JsonObject json_object);

        DualBlades(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series
        );
    }

    [default_interface]
    runtimeclass Lance : Weapon
    {
        static Lance Parse(Windows.Data.Json.JsonObject json_object);

        Lance(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series
        );
    }

    [default_interface]
    runtimeclass GreatSword : Weapon
    {
        static GreatSword Parse(Windows.Data.Json.JsonObject json_object);

        GreatSword(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series
        );
    }

    enum AmmoKind
    {
        Normal,
        Pierce,
        Spread,
        Slicing,
        Sticky,
		Cluster,
        Wyvern,
		Poison,
		Paralysis,
        Sleep,
        Flaming,
        Water,
        Freeze,
		Thunder,
        Dragon,
        Recover,
        Demon,
        Armor,
        Exhaust,
        Tranq
    };

    runtimeclass LightBowgunAmmo
    {
        static LightBowgunAmmo Parse(Windows.Data.Json.JsonObject json_object);

		LightBowgunAmmo(AmmoKind kind, Int32 level, Int32 capacity, Boolean rapid);

        AmmoKind Kind{ get; };
        Int32 Level{ get; };
		Int32 Capacity{ get; };
        Boolean Rapid{ get; };
    }

    enum LightBowgunSpecialAmmo
    {
        Wyvernblast,
        Adhesive
    };

    runtimeclass LightBowgun : Weapon
    {
        static LightBowgun Parse(Windows.Data.Json.JsonObject json_object);

        LightBowgun(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
			Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series,
            Windows.Foundation.Collections.IVector<LightBowgunAmmo> ammo,
            LightBowgunSpecialAmmo special_ammo
        );

		Windows.Foundation.Collections.IVector<LightBowgunAmmo> Ammo{ get; };
        LightBowgunSpecialAmmo SpecialAmmo{ get; };
	}

    enum GunlanceShell
    {
        Normal,
        Wide,
        Long
    };

    runtimeclass Gunlance : Weapon
    {
        static Gunlance Parse(Windows.Data.Json.JsonObject json_object);

        Gunlance(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series,
            GunlanceShell shell,
            Int32 shell_level
        );

        GunlanceShell Shell{ get; };
        Int32 ShellLevel{ get; };
    }

    [default_interface]
    runtimeclass LongSword : Weapon
    {
        static LongSword Parse(Windows.Data.Json.JsonObject json_object);

        LongSword(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series
        );
    }

    [default_interface]
    runtimeclass Hammer : Weapon
    {
        static Hammer Parse(Windows.Data.Json.JsonObject json_object);

        Hammer(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series
        );
    }

    enum SwitchAxePhial
    {
        Power,
        Element,
        Dragon,
        Exhaust,
        Parayze,
        Poison
    };

    runtimeclass Phial
    {
        static Phial Parse(Windows.Data.Json.JsonObject json_object);

        Phial(SwitchAxePhial kind, WeaponDamage damage);

        SwitchAxePhial Kind{ get; };
	    WeaponDamage Damage{ get; };
    }

    runtimeclass SwitchAxe : Weapon
    {
        static SwitchAxe Parse(Windows.Data.Json.JsonObject json_object);

        SwitchAxe(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series,
            Phial phial
		);

        Phial Phial{ get; };
	}

    runtimeclass HeavyBowgunAmmo
    {
        static HeavyBowgunAmmo Parse(Windows.Data.Json.JsonObject json_object);

        HeavyBowgunAmmo(AmmoKind kind, Int32 level, Int32 capacity);

        AmmoKind Kind{ get; };
        Int32 Level{ get; };
        Int32 Capacity{ get; };
    }

    runtimeclass HeavyBowgun : Weapon
    {
        static HeavyBowgun Parse(Windows.Data.Json.JsonObject json_object);

        HeavyBowgun(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series,
            Windows.Foundation.Collections.IVector<HeavyBowgunAmmo> ammo
        );

        Windows.Foundation.Collections.IVector<HeavyBowgunAmmo> Ammo{ get; };
    }

    [default_interface]
    runtimeclass SwordShield : Weapon
    {
        static SwordShield Parse(Windows.Data.Json.JsonObject json_object);

        SwordShield(
            Int32 id,
            Int32 game_id,
            WeaponKind kind,
            String name,
            Int32 rarity,
            WeaponDamage damage,
            Windows.Foundation.Collections.IVector<WeaponSpecial> specials,
            Sharpness sharpness,
            Windows.Foundation.Collections.IVector<Int32> handicraft,
            Windows.Foundation.Collections.IVector<SkillRank> skills,
            Int32 defense_bonus,
            Windows.Foundation.IReference<Elderseal> elderseal,
            Int32 affinity,
            Windows.Foundation.Collections.IVector<Int32> slots,
            WeaponCrafting crafting,
            WeaponSeries series
        );
    }

    // Database Urls
    [default_interface]
    runtimeclass Api
    {
        Api();
        Api(String locale);

        String BaseUrl{ get; };
        String Locale;

        String ArmorUrl();
        String ArmorSetsUrl();
        String CharmsUrl();
        String DecorationsUrl();
        String ItemsUrl();
        String SkillsUrl();
        String WeaponsUrl();
    }

    // Json Parser
    delegate Object JsonValueTransformer(Windows.Data.Json.IJsonValue json_value);
    delegate Object JsonObjectTransformer(Windows.Data.Json.JsonObject json_object);

    static runtimeclass JsonParser
    {       
        static Int32 GetNamedInt32(Windows.Data.Json.JsonObject json_object, String key);

        static String TryGetNamedString(Windows.Data.Json.JsonObject json_object, String key);
        static Windows.Foundation.IReference<Int32> TryGetNamedInt32(Windows.Data.Json.JsonObject json_object, String key);
        
        static Windows.Foundation.Collections.IVector<Object> ParseJsonArray(Windows.Data.Json.JsonArray json_array, JsonValueTransformer transformer);
        static Windows.Foundation.Collections.IVector<Int32> ParseNamedInt32Array(Windows.Data.Json.JsonObject json_object, String key);

        static Object TryParseNamedObject(Windows.Data.Json.JsonObject json_object, String key, JsonObjectTransformer transformer);
        static Windows.Foundation.Collections.IVector<Object> TryParseNamedArray(Windows.Data.Json.JsonObject json_object, String key, JsonValueTransformer transformer);
        static Windows.Foundation.Collections.IVector<Int32> TryParseNamedInt32Array(Windows.Data.Json.JsonObject json_object, String key);

        static WeaponSpecial ParseWeaponSpecial(Windows.Data.Json.IJsonValue json_value);
        static Windows.Foundation.Collections.IVector<WeaponSpecial> ParseWeaponSpecials(Windows.Data.Json.JsonObject json_object);
        static Weapon ParseWeapon(Windows.Data.Json.JsonObject json_object);

        static Windows.Foundation.Collections.IVector<Armor> ParseArmors(Windows.Data.Json.JsonArray json_array);
        static Windows.Foundation.Collections.IVector<ArmorSetBonusRank> ParseArmorSetBonusRanks(Windows.Data.Json.JsonArray json_array);
        static Windows.Foundation.Collections.IVector<SkillRank> ParseSkillRanks(Windows.Data.Json.JsonArray json_array);
        static Windows.Foundation.Collections.IVector<BowCoating> ParseBowCoatings(Windows.Data.Json.JsonObject json_object);
        static Windows.Foundation.Collections.IVector<LightBowgunAmmo> ParseLightBowgunAmmos(Windows.Data.Json.JsonObject json_object);
        static Windows.Foundation.Collections.IVector<HeavyBowgunAmmo> ParseHeavyBowgunAmmos(Windows.Data.Json.JsonObject json_object);
    }

    [default_interface]
    runtimeclass Database
    {
        Database();
        Database(String locale);

        Windows.Foundation.IAsyncOperation<String> GetVersionAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetJsonArrayAsync(String url);
        Windows.Foundation.IAsyncAction SaveUrlToFile(String url, String file_name);
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetArmorsJsonAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetArmorSetsJsonAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetCharmsJsonAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetDecorationsJsonAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetItemsJsonAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetSkillsJsonAsync();
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonArray> GetWeaponsJsonAsync();

        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Armor> > GetArmorsAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<ArmorSet> > GetArmorSetsAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Charm> > GetCharmsAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Decoration> > GetDecorationsAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Item> > GetItemsAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Skill> > GetSkillsAsync();
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Weapon> > GetWeaponsAsync();
    }

    static runtimeclass EnumMap
    {
        static Color ColorMap(String str);
        static ItemIconKind ItemIconKindMap(String str);
        static SkillKind SkillKindMap(String str);
        static SkillIconKind SkillIconKindMap(String str);
        static Element ElementMap(String str);
        static Status StatusMap(String str);
        static ArmorKind ArmorKindMap(String str);
        static Rank RankMap(String str);
        static DecorationKind DecorationKindMap(String str);
        static Elderseal EldersealMap(String str);
        static Windows.Foundation.IReference<Elderseal> TryEldersealMap(Windows.Data.Json.JsonObject json_object, String key);
        static WeaponKind WeaponKindMap(String str);
        static ChargeBladePhial ChargeBladePhialMap(String str);
        static SwitchAxePhial SwitchAxePhialMap(String str);
        static HuntingHornNote HuntingHornNoteMap(String str);
        static HuntingHornBubbleKind HuntingHornBubbleKindMap(String str);
        static AmmoKind AmmoKindMap(String str);
        static HuntingHornWaveKind HuntingHornWaveKindMap(String str);
        static BowCoating BowCoatingMap(String str);
        static GunlanceShell GunlanceShellMap(String str);
        static LightBowgunSpecialAmmo LightBowgunSpecialAmmoMap(String str);
    }
}
